import Head from 'next/head'
import { GameDesignLoader } from '@/components/GameDesignLoader'
import AppHeader from '@/components/AppHeader'
import { Box } from '@mui/material'


export default function GameLoaderPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: 'flex' }} paddingTop={'2rem'}>
        <AppHeader />
        <Box component='main'>
          <GameDesignLoader />
        </Box>
      </Box>

    </>
  )
}
