import AppHeader from '@/components/AppHeader'
import { LinkButton } from '@/components/LinkButton'
import { Box } from '@mui/material'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: 'flex' }} paddingTop={'2rem'}>
        <AppHeader />
        <Box component='main'>
          <div>
            <LinkButton href="./game-loader" variant='contained'>game loader</LinkButton>
          </div>
          <div>
            <LinkButton href="./prebuilt-game" variant='contained'>prebuilt game</LinkButton>
          </div>
        </Box>
      </Box>
    </>
  )
}
