import Head from 'next/head'
import { GameDesignPlayer } from '@/components/GameDesignPlayer'
import { prebuiltGameDesign } from '@/data/fullGame'
import { imageAssets } from '@/data/images'
import { soundAssets } from '@/data/sounds'
import AppHeader from '@/components/AppHeader'
import { Box } from '@mui/material'


export default function GameLoaderPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Box sx={{ display: 'flex' }} paddingTop={'2rem'}>
        <AppHeader />
        <Box component='main'>
          <GameDesignPlayer
            gameDesign={prebuiltGameDesign}
            imageAssets={imageAssets}
            soundAssets={soundAssets}
          />
        </Box>
      </Box>
    </>
  )
}
